#ifndef _GAME_SETTINGS_
#define _GAME_SETTINGS_

enum GameSettings
{
	MAX_NUMBER_ON_BOARD = 60,
	STEPS_FOR_NEW_NUMBER = 5,
	POINT_TO_WIN_THE_GAME = 4,
	SANKE_ONE_BODY_FILL = '@',
	SANKE_TWO_BODY_FILL = '#',
};

#endif
