#ifndef _GAME_SETTINGS_
#define _GAME_SETTINGS_
#include <string>



enum GameSettings
{
	MAX_NUMBER_ON_BOARD = 60,
	STEPS_FOR_NEW_NUMBER = 5,
	POINT_TO_WIN_THE_GAME = 12,
	SANKE_ONE_BODY_FILL = '@',
	SANKE_TWO_BODY_FILL = '#',
	GUN_CHAR = '*',
	FLYING_ROW = '!',
	FLYING_COL = '$',
	NUMBER_EATER = '%',
	GUN_AMMO_INITIAL = 5,
	RELIVE_AFTER_STEPS = 25,
	SNAKE_START_SIZE = 3,
};

enum Direction
{
	DIRECTION_UP = 0,
	DIRECTION_DOWN = 1,
	DIRECTION_LEFT = 2,
	DIRECTION_RIGHT = 3
};

#endif
